version: '3'
services:
 hardware_analysis:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/root/hardware_analysis
      - "/dev:/dev"
    privileged: true
    container_name: hardware_analysis
    networks:
      - analysis_net
    depends_on:
      firmadyne_db:
        condition: service_healthy
 firmadyne_db:
    image: postgres:latest
    restart: always
    volumes:
      - /var/lib/postgres
    environment:
      POSTGRES_DB: firmware
      POSTGRES_USER: firmadyne
      POSTGRES_PASSWORD: firmadyne
    networks:
      - analysis_net
    ports:
      - "5431:5432"
    container_name: firmadyne_db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "firmadyne"]
      interval: 30s
      timeout: 30s
      retries: 3
networks:
 analysis_net:
